apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pou8yj7ir-java-springboot
  janus-idp.io/tekton: pou8yj7ir-java-springboot
  backstage.io/kubernetes-id: pou8yj7ir-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pou8yj7ir-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
